#!/bin/bash
# stdin: VERSION_TEMPLATE; stdout: created Html
# Note: don't use stdout for other (err, info, etc.) output!
. Scripts/util.src
VERSION_DIR=$1
URL_PARAMS=$2
MINIFY_OPTION=${3:-"--minified"}

SED_STR_VERSION_DIR='s/_VERSION_DIR_/'$VERSION_DIR'/'
SED_STR_URL_PARAMS='s/_URL_PARAMS_/'$URL_PARAMS'/'
SED_STR_MINIFY='s/(\.js|css)_URL_PARAMS_/\1-min'$URL_PARAMS'/'
SED_STR_MINIFY_JS='s/\.js_URL_PARAMS_/-min\.js'$URL_PARAMS'/'
SED_STR_MINIFY_CSS='s/\.css_URL_PARAMS_/-min\.css'$URL_PARAMS'/'

info "VERSION_DIR: $VERSION_DIR" "URL_PARAMS: $URL_PARAMS"
info "SED_STR_VERSION_DIR: $SED_STR_VERSION_DIR"
info "SED_STR_URL_PARAMS: $SED_STR_URL_PARAMS"

if [[ $MINIFY_OPTION == "--minified" ]]
then
    sed -e $SED_STR_MINIFY_JS -e $SED_STR_MINIFY_CSS -e $SED_STR_VERSION_DIR -e $SED_STR_URL_PARAMS
else
    sed -e $SED_STR_VERSION_DIR -e $SED_STR_URL_PARAMS
fi
