#!/bin/bash
# fills in RYT_INSTALL_DIR and SERVER_TO_PUSH_TO into lftp scripts

# source utils
. Scripts/util.src

# string to be replaced in input file
toBeReplacedStr=_RYT_DATA_DIRNAME_

if [[ $# -ne 3 ]]
then
    usage 'FILE RYT_INSTALL_DIR SERVER_TO_PUSH_TO'
fi
FILE=$1
RYT_INSTALL_DIR=$2
SERVER_TO_PUSH_TO=$3

if [[ -n "$RYT_INSTALL_DIR" ]]
then
    info "Given RYT_INSTALL_DIR: '$RYT_INSTALL_DIR'."
else
    error "empty RYT_INSTALL_DIR."
fi
if [[ -n "$SERVER_TO_PUSH_TO" ]]
then
    info "Given SERVER_TO_PUSH_TO: '$SERVER_TO_PUSH_TO'."
else
    error "empty SERVER_TO_PUSH_TO."
fi

SED_STR_RYT_INSTALL_DIR="s%_RYT_INSTALL_DIR_%$RYT_INSTALL_DIR%"
SED_STR_SERVER_TO_PUSH_TO="s/_SERVER_TO_PUSH_TO_/$SERVER_TO_PUSH_TO/"

sed -e $SED_STR_RYT_INSTALL_DIR \
    -e $SED_STR_SERVER_TO_PUSH_TO \
    $FILE || error 'fail'
