#!/bin/bash
# fills in RYT data dir into input file

# source utils
. Scripts/util.src

# string to be replaced in input file
toBeReplacedStr=_RYT_DATA_DIRNAME_

if [[ $# -ne 2 ]]
then
    usage 'FILE RYT_DATA_DIRNAME'
fi
FILE=$1
DIRNAME=$2

if [[ -n "$DIRNAME" ]]
then
    info "Given RYT_DATA_DIRNAME: '$DIRNAME'."
else
    error "empty RYT_DATA_DIRNAME."
fi

SED_STR_RYT_DATA_DIRNAME="s/$toBeReplacedStr/$DIRNAME/"

sed -e $SED_STR_RYT_DATA_DIRNAME $FILE || error 'fail'
