#!/bin/bash
# fills in admin password into input file

# source utils
. Scripts/util.src

# string to be replaced in input file
toBeReplacedStr=_RYT_ADMIN_PASSWORD_

if [[ $# -ne 2 ]]
then
    usage 'FILE PASSWORD'
fi
FILE=$1
adminPassword=$2

if [[ -z "$adminPassword" ]]
then
    error "empty admin password."
fi

SED_STR_ADMIN_PASSWORD="s/$toBeReplacedStr/$adminPassword/"

sed -e $SED_STR_ADMIN_PASSWORD $FILE || error 'fail'
