#!/bin/bash
# asks for password and echoes it to stdout

# source utils
. Scripts/util.src

input 'adminPassword' "\n  Please give admin password for storing public projects:"

if [[ -n "$adminPassword" ]]
then
    info "Given password: '$adminPassword'."
else
    error "empty admin password."
fi

echo -n $adminPassword
