#!/bin/bash
# asks for password and echoes it to stdout

# source utils
. Scripts/util.src

input 'adminPassword' "\n  RYT admin password to be used for storing public projects:"

noPercentageRE='^[^%]*$'
if [[ -n $adminPassword ]]
then
    if [[ $adminPassword =~ $noPercentageRE ]]
    then
        info "Given password: '$adminPassword'."
    else
        error "'%' in given password: '$adminPassword' not allowed."
    fi
else
    error "empty admin password."
fi

echo -n $adminPassword
